version: '3.8'

services:
  app:
    build: .
    container_name: apiserver
    ports:
      - 8000:8000
    networks:
      - "sql-network"
    healthcheck:
      test: ["CMD", "python", "-c",  "import requests; requests.get('http://localhost:8000')"]
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mysql
    container_name: sqlserver
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pok", "ping", "-h", "localhost"]
    networks:
      - "sql-network"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_RELATIVE_PATH=/aiod-auth
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_USERS=same_file
    ports:
      - 8080:8080 
    networks:
      - "sql-network"
    volumes:
     - ./keycloak:/opt/keycloak/data/import 
 
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - "sql-network"
    external_links:
      - keycloak
    depends_on:
      app:
        condition: service_healthy

networks:
  sql-network:
    driver: bridge

