version: '3'

services:
  app:
    build: Dockerfile
    container_name: apiserver
    ports:
      - 8000:8000
    networks:
      - sql-network
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mysql
    container_name: sqlserver
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - sql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    entrypoint: /opt/keycloak/bin/kc.sh start
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_RELATIVE_PATH=/aiod-auth
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
    ports:
      - 8080:8080 
    volumes:
     - ./keycloak:/opt/keycloak/data/import 

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    external_links:
      - keycloak

networks:
  sql-network:
    driver: bridge
